// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oi6d2C3_dDuAXLImUpBMxvOS2_Ympu0',
    appId: '1:396383174257:web:862311ad6196498e7ea5d0',
    messagingSenderId: '396383174257',
    projectId: 'mygymbro-f072a',
    authDomain: 'mygymbro-f072a.firebaseapp.com',
    databaseURL: 'https://mygymbro-f072a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mygymbro-f072a.appspot.com',
    measurementId: 'G-727E4FS1CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBp3u2Ipid7hvRdYRMrsJNVkpECAHZK0w',
    appId: '1:396383174257:android:cd3a1767a3d4b1cd7ea5d0',
    messagingSenderId: '396383174257',
    projectId: 'mygymbro-f072a',
    databaseURL: 'https://mygymbro-f072a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mygymbro-f072a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXWvLp4iN9xsDx6tEywmwuk8FC8qDJJrY',
    appId: '1:396383174257:ios:e26309f0cfed2ec07ea5d0',
    messagingSenderId: '396383174257',
    projectId: 'mygymbro-f072a',
    databaseURL: 'https://mygymbro-f072a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mygymbro-f072a.appspot.com',
    iosClientId: '396383174257-3lcsgmfgpq5rckradikhemteno61laou.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGymBro',
  );
}
